name: user_onboarding
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.2 
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  path_provider: ^2.0.15
  uuid: ^4.0.0
  connectivity_plus: ^4.0.1
  provider: ^6.1.1
  postgres: ^2.6.1
  dotenv: ^4.1.0
  flutter_dotenv: ^5.1.0 
  supabase_flutter: ^2.0.0  
  table_calendar: ^3.0.9
  speech_to_text: ^7.3.0 
  #health: ^10.2.0
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  pedometer: ^4.0.2
  
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/icon/